# Generated by Django 5.0.4 on 2024-04-20 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GDSC', '0003_remove_item_description_remove_item_name_item_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='methodPreferences',
            new_name='methodPreference',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='school',
            new_name='schoolOrJob',
        ),
    ]
